new search frontend prototpye, but not used ;-)

diff --git a/distrib/bin/split_doc b/distrib/bin/split_doc
--- a/distrib/bin/split_doc
+++ b/distrib/bin/split_doc
@@ -1,53 +1,89 @@
 #!/bin/sh
+#
+# Copyright (C) 2000 Ken'ichi Fukamachi
+#          All rights reserved. 
+#
+# $Id$
+#
 
-LINK=$1
-
-if [ X$LINK = X ]
-then
-	echo "$0: require one argument (dst to symlink)"
-	exit 1
-fi
+### configurations
+tmp=/tmp/import$$
+trap "rm -f $tmp" 0 1 3 15
 
 GEN="perl distrib/bin/html_split.pl"
 
-if [ -d var/db -a ! -h var/db ]
-then
-	echo "var/db directory exists! STOP "; 
+
+### import variables
+chdir $FML
+make __import_variables > $tmp
+. $tmp
+
+
+### MAIN
+if [ ! -d $WWW_DB_DIR ]; then
+	echo "Error: WWW_DB_DIR not defined!"; 
 	exit 1
-else
-	rm -f var/db
-	ln -s $LINK var/db
 fi
 
-tmp=/tmp/splitdoc$$
+if [ X$BRANCH = X ]; then
+	echo "Error: BRANCH not defined!"; 
+	exit 1
+fi
 
-trap "rm -f $tmp" 0 1 3 15
+# target directory
+TARGET_DIR=var/db/search.index
 
-(cd var/html/; echo * | tr ' ' '\012' |perl -nle 'print unless -l $_'> $tmp )
+test -d $TARGET_DIR || mkdirhier $TARGET_DIR
 
+
+echo "rm -f $TARGET_DIR/*"; sleep 1
+rm -f $TARGET_DIR/* >/dev/null 2>&1 
+
+
+# var/html is hard coding ;-)
+(
+   chdir var/html/;
+   echo * | tr ' ' '\012' |perl -nle 'print unless -l $_'> $tmp
+)
+
+
+
+# here we go!
 for dir in `cat $tmp`
 do
-   if [ -d var/html/$dir ]	
-   then
-	if [ ! -d var/db/$dir -o \
-	var/html/$dir/index.html -nt var/db/$dir/.touch ]
-	then
-	   $GEN -R ../../$dir/ -U http://www.fml.org/fml/$dir \
-		-D var/db/$dir var/html/$dir/[i0-9]*html
+   if [ -d var/html/$dir ]; then
+	if [ ! -d ${TARGET_DIR}/$dir -o \
+	var/html/$dir/index.html -nt ${TARGET_DIR}/$dir/.touch ]; then
+
+	   echo "rm -f ${TARGET_DIR}/$dir/\*"
+	   sleep 1
+	   rm -f ${TARGET_DIR}/$dir/*
+
+	   echo ""
+	   echo "$GEN -R ../../../$dir/ -U http://www.fml.org/fml/$dir "
+	   echo "     -D ${TARGET_DIR}/$dir var/html/$dir/[i0-9]*html"
+	   echo ""
+
+	   $GEN -R ../../../$dir/ -U http://www.fml.org/fml/$dir \
+		-D ${TARGET_DIR}/$dir var/html/$dir/[i0-9]*html
+
+	   stat=` apply echo ${TARGET_DIR}/$dir/[0-9]*  2>/dev/null `
+
+	   if [ "X$stat" = X ];then
+		echo cp var/html/$dir/[i0-9]*html ${TARGET_DIR}/$dir 
+		cp var/html/$dir/[i0-9]*html ${TARGET_DIR}/$dir 
+	   fi
 	fi
 
-	touch var/db/$dir/.touch
+	touch ${TARGET_DIR}/$dir/.touch
 
-   elif [ -f var/html/$dir ]
-   then
-	rm -f var/db/$dir
-	cp -p var/html/$dir var/db/$dir
+   elif [ -f var/html/$dir ]; then
+
+	# always copy
+	rm -f ${TARGET_DIR}/$dir
+	echo cp var/html/$dir ${TARGET_DIR}/$dir
+	cp var/html/$dir ${TARGET_DIR}/$dir
    fi
 done
-
-echo ""
-echo "perl distrib/bin/find_older.pl |perl -nple unlink"
-echo ""
-perl distrib/bin/find_older.pl |perl -nple unlink
 
 exit 0;
